import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  signer:   [{type: 'autogenerated', dirName: 'signer'}],
  signerEn: [{type: 'autogenerated', dirName: 'en/signer'}],
};

export default sidebars;