import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the generated .NET API reference (served at /api by its own docs
// plugin instance — see docusaurus.config.ts). Autogenerated from the api-docs/
// tree, so every namespace folder becomes a collapsible section.
const sidebars: SidebarsConfig = {
  apiRef: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
