import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebars for the English docs instance (docs/en, served at /en-us/articles).
// Dir names are relative to docs/en.
const sidebars: SidebarsConfig = {
  pkiGuideEn:    [{type: 'autogenerated', dirName: 'pki-guide'}],
  welcomeEn:     [{type: 'autogenerated', dirName: 'welcome'}],
  webPkiEn:      [{type: 'autogenerated', dirName: 'web-pki'}],
  restPkiEn:     [{type: 'autogenerated', dirName: 'rest-pki'}],
  restPkiCoreEn: [{type: 'autogenerated', dirName: 'rest-pki-core'}],
  pkiSdkEn: [
    {type: 'autogenerated', dirName: 'pki-sdk'},
    // Links to the generated .NET API reference (served at /en-us/api by its
    // own docs plugin instance — see docusaurus.config.ts).
    {type: 'link', label: 'API Reference', href: '/en-us/api/'},
  ],
  pkiExpressEn:  [{type: 'autogenerated', dirName: 'pki-express'}],
  signerEn:      [{type: 'autogenerated', dirName: 'signer'}],
  bulkSignerEn:  [{type: 'autogenerated', dirName: 'bulk-signer'}],
  ampliaEn:      [{type: 'autogenerated', dirName: 'amplia'}],
  ampliaRegEn:   [{type: 'autogenerated', dirName: 'amplia-reg'}],
  grantIdEn:     [{type: 'autogenerated', dirName: 'grant-id'}],
  scannerEn:     [{type: 'autogenerated', dirName: 'scanner'}],
  pscEn:         [{type: 'autogenerated', dirName: 'psc'}],
  tsaEn:         [{type: 'autogenerated', dirName: 'tsa'}],
  digiplomaEn:   [{type: 'autogenerated', dirName: 'digiploma'}],
};

export default sidebars;
