import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebars for the Portuguese docs instance (docs/, served at /articles).
// English sidebars live in sidebarsEn.ts (docs-en instance).
const sidebars: SidebarsConfig = {
  pkiGuide:      [{type: 'autogenerated', dirName: 'pki-guide'}],
  welcome:       [{type: 'autogenerated', dirName: 'welcome'}],
  webPki:        [{type: 'autogenerated', dirName: 'web-pki'}],
  restPki:       [{type: 'autogenerated', dirName: 'rest-pki'}],
  restPkiCore:   [{type: 'autogenerated', dirName: 'rest-pki-core'}],
  pkiSdk: [
    {type: 'autogenerated', dirName: 'pki-sdk'},
    // Links to the generated .NET API reference (served at /api by its own docs
    // plugin instance — see docusaurus.config.ts).
    {type: 'link', label: 'API Reference', href: '/api/'},
  ],
  pkiExpress:    [{type: 'autogenerated', dirName: 'pki-express'}],
  signer:        [{type: 'autogenerated', dirName: 'signer'}],
  bulkSigner:    [{type: 'autogenerated', dirName: 'bulk-signer'}],
  amplia:        [{type: 'autogenerated', dirName: 'amplia'}],
  ampliaReg:     [{type: 'autogenerated', dirName: 'amplia-reg'}],
  grantId:       [{type: 'autogenerated', dirName: 'grant-id'}],
  scanner:       [{type: 'autogenerated', dirName: 'scanner'}],
  psc:           [{type: 'autogenerated', dirName: 'psc'}],
  tsa:           [{type: 'autogenerated', dirName: 'tsa'}],
  digiploma:     [{type: 'autogenerated', dirName: 'digiploma'}],
};

export default sidebars;
