import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pkiGuide:      [{type: 'autogenerated', dirName: 'pki-guide'}],
  pkiGuideEn:    [{type: 'autogenerated', dirName: 'en/pki-guide'}],
  welcome:       [{type: 'autogenerated', dirName: 'welcome'}],
  welcomeEn:     [{type: 'autogenerated', dirName: 'en/welcome'}],
  webPki:        [{type: 'autogenerated', dirName: 'web-pki'}],
  webPkiEn:      [{type: 'autogenerated', dirName: 'en/web-pki'}],
  restPki:       [{type: 'autogenerated', dirName: 'rest-pki'}],
  restPkiEn:     [{type: 'autogenerated', dirName: 'en/rest-pki'}],
  restPkiCore:   [{type: 'autogenerated', dirName: 'rest-pki-core'}],
  restPkiCoreEn: [{type: 'autogenerated', dirName: 'en/rest-pki-core'}],
  pkiSdk: [
    {type: 'autogenerated', dirName: 'pki-sdk'},
    // Links to the generated .NET API reference (served at /api by its own docs
    // plugin instance — see docusaurus.config.ts).
    {type: 'link', label: 'API Reference', href: '/api/'},
  ],
  pkiSdkEn: [
    {type: 'autogenerated', dirName: 'en/pki-sdk'},
    {type: 'link', label: 'API Reference', href: '/en/api/'},
  ],
  pkiExpress:    [{type: 'autogenerated', dirName: 'pki-express'}],
  pkiExpressEn:  [{type: 'autogenerated', dirName: 'en/pki-express'}],
  signer:        [{type: 'autogenerated', dirName: 'signer'}],
  signerEn:      [{type: 'autogenerated', dirName: 'en/signer'}],
  bulkSigner:    [{type: 'autogenerated', dirName: 'bulk-signer'}],
  bulkSignerEn:  [{type: 'autogenerated', dirName: 'en/bulk-signer'}],
  amplia:        [{type: 'autogenerated', dirName: 'amplia'}],
  ampliaEn:      [{type: 'autogenerated', dirName: 'en/amplia'}],
  ampliaReg:     [{type: 'autogenerated', dirName: 'amplia-reg'}],
  ampliaRegEn:   [{type: 'autogenerated', dirName: 'en/amplia-reg'}],
  grantId:       [{type: 'autogenerated', dirName: 'grant-id'}],
  grantIdEn:     [{type: 'autogenerated', dirName: 'en/grant-id'}],
  scanner:       [{type: 'autogenerated', dirName: 'scanner'}],
  scannerEn:     [{type: 'autogenerated', dirName: 'en/scanner'}],
  psc:           [{type: 'autogenerated', dirName: 'psc'}],
  pscEn:         [{type: 'autogenerated', dirName: 'en/psc'}],
  tsa:           [{type: 'autogenerated', dirName: 'tsa'}],
  tsaEn:         [{type: 'autogenerated', dirName: 'en/tsa'}],
  digiploma:     [{type: 'autogenerated', dirName: 'digiploma'}],
  diplomaEn:     [{type: 'autogenerated', dirName: 'en/digiploma'}],
};

export default sidebars;